### ISSUE TITLE
The SCRIPT_NAME hack breaks standard setups.

### ISSUE THREAD

**Issue by urkle** [teambox/omniauth-redbooth#4]
The hack added in commit 037c36b07ba6 breaks standard setups (non-mounted).  With that hack in place the generated redirect_uri that was sent to redbooth was incorrect and contained two slashes  (e.g..  https://mysite.como//oauth/success ). This then becomes rejected by Redbooth as it doesn't match the redirect URI we specified in the app.

Further it breaks other aspects of the application as the hack was done in a global manner.  So our Grape based API which has it's own oauth system in place was generating incorrect signatures as it had a urls with an extra / (that the clients did not have of course). 

This hack does not belong in a gem like this as it has nothing to do with "redbooth" or omniauth, but how things were mounted in the contributors setup and it needs to be removed.

**Comment by franciscoj** [comment]
We'll have a look ASAP, thanks.

**Comment by franciscoj** [comment]
@urkle I removed that here https://github.com/teambox/omniauth-redbooth/pull/5

Thanks for your feedback!

**Comment by franciscoj** [comment]
@urkle just released version 1.0.1 which fixes this dirty hack https://github.com/teambox/omniauth-redbooth/blob/develop/CHANGELOG.md#101---2015-11-26
